<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Tracking.Core\Tracking.Core.csproj" />
    <ProjectReference Include="..\..\Core\Tracking.Network\Tracking.Network.csproj" />
    <ProjectReference Include="..\..\Core\Tracking.PluginLoader\Tracking.PluginLoader.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Tracking.Storage\Tracking.Storage.csproj" />
  </ItemGroup>

</Project>